### ISSUE TITLE
AUR build fail

### ISSUE THREAD

**Issue by tabledrop** [KotatsuApp/kotatsu-dl-gui#6]
Hello,

For context, I use EndeavourOS. When using an AUR helper (like `yay`), I get the following build error:
```
> Task :proguardReleaseJars FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':proguardReleaseJars'.
> External tool execution failed:
  * Command: [/usr/lib/jvm/java-20-amazon-corretto/bin/java, -cp, "/home/tabledrop/.gradle/caches/modules-2/files-2.1/com.guardsquare/proguard-gradle/7.2.2/3ee8f512db2bee70d3eca9be10986d96404dc2f0/proguard-gradle-7.2.2.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/com.github.zafarkhaja/java-semver/0.9.0/59a83ca73c72a5e25b3f0b1bb305230a11000329/java-semver-0.9.0.jar:/home/tablefrop/.gradle/caches/modules-2/files-2.1/com.guardsquare/proguard-base/7.2.2/5c67dd9184bfb7d01b082b45bf3a6599b43d5c25/proguard-base-7.2.2.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.10/e80fe6ac3c3573a80305f5ec43f86b829e8ab53d/kotlin-stdlib-jdk8-1.6.10.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.5/f645ed69d595b24d4cf8b3fbb64cc505bede8829/gson-2.8.5.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/com.guardsquare/proguard-core/9.0.1/b1c26f3a6fc947a1bdfa67fd8c96230df0471156/proguard-core-9.0.1.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.17.1/779f60f3844dadc3ef597976fcb1e5127b1f343d/log4j-core-2.17.1.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.17.1/d771af8e336e372fb5399c99edabe0919aeaf5b2/log4j-api-2.17.1.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/org.json/json/20211205/47032dcf2f69880f07dab3dc60b4b0ad97318308/json-20211205.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-metadata-jvm/0.4.1/834f5bdb32c504ee72fa50750ad16ab1679c19e6/kotlinx-metadata-jvm-0.4.1.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.10/b8af3fe6f1ca88526914929add63cf5e7c5049af/kotlin-stdlib-1.6.10.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.10/c118700e3a33c8a0d9adc920e9dec0831171925/kotlin-stdlib-common-1.6.10.jar:/home/tabledrop/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar", proguard.ProGuard, -include, "/home/tabledrop/.cache/yay/kotatsu-dl-git/src/kotatsu-dl/build/compose/tmp/proguardReleaseJars/root-config.pro"]
  * Working dir: []
  * Exit code: 1
  * Standard output log: /home/tabledrop/.cache/yay/kotatsu-dl-git/src/kotatsu-dl/build/compose/logs/proguardReleaseJars/java-2023-11-06-20-48-43-out.txt
  * Error log: /home/tabledrop/.cache/yay/kotatsu-dl-git/src/kotatsu-dl/build/compose/logs/proguardReleaseJars/java-2023-11-06-20-48-43-err.txt
```

When looking at the `/build/compose/logs/proguardReleaseJars/` folder for the two error log files, `java-2023-11-06-20-48-43-err.txt` is an empty file, while `java-2023-11-06-20-48-43-out.txt` contains the following:
```
ProGuard, version 7.2.2
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of program class [module-info]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/AL2.0]
Note: duplicate definition of resource file [META-INF/LGPL2.1]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/AL2.0]
Note: duplicate definition of resource file [META-INF/LGPL2.1]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of program class [com.sun.jna.AltCallingConvention]
Note: duplicate definition of program class [com.sun.jna.Callback$UncaughtExceptionHandler]
Note: duplicate definition of program class [com.sun.jna.Callback]
Note: duplicate definition of program class [com.sun.jna.CallbackParameterContext]
Note: duplicate definition of program class [com.sun.jna.CallbackProxy]
Note: duplicate definition of program class [com.sun.jna.CallbackReference$AttachOptions]
Note: duplicate definition of program class [com.sun.jna.CallbackReference$DefaultCallbackProxy]
Note: duplicate definition of program class [com.sun.jna.CallbackReference$NativeFunctionHandler]
Note: duplicate definition of program class [com.sun.jna.CallbackReference]
Note: duplicate definition of program class [com.sun.jna.CallbackResultContext]
Note: duplicate definition of program class [com.sun.jna.CallbackThreadInitializer]
Note: duplicate definition of program class [com.sun.jna.DefaultTypeMapper$Entry]
Note: duplicate definition of program class [com.sun.jna.DefaultTypeMapper]
Note: duplicate definition of program class [com.sun.jna.ELFAnalyser$1]
Note: duplicate definition of program class [com.sun.jna.ELFAnalyser$ArmAeabiAttributesTag$ParameterType]
Note: duplicate definition of program class [com.sun.jna.ELFAnalyser$ArmAeabiAttributesTag]
Note: duplicate definition of program class [com.sun.jna.ELFAnalyser$ELFSectionHeaderEntry]
Note: duplicate definition of program class [com.sun.jna.ELFAnalyser$ELFSectionHeaders]
Note: duplicate definition of program class [com.sun.jna.ELFAnalyser]
Note: duplicate definition of program class [com.sun.jna.FromNativeContext]
Note: duplicate definition of program class [com.sun.jna.FromNativeConverter]
Note: duplicate definition of program class [com.sun.jna.Function$NativeMappedArray]
Note: duplicate definition of program class [com.sun.jna.Function$PointerArray]
Note: duplicate definition of program class [com.sun.jna.Function$PostCallRead]
Note: duplicate definition of program class [com.sun.jna.Function]
Note: duplicate definition of program class [com.sun.jna.FunctionMapper]
Note: duplicate definition of program class [com.sun.jna.FunctionParameterContext]
Note: duplicate definition of program class [com.sun.jna.FunctionResultContext]
Note: duplicate definition of program class [com.sun.jna.IntegerType]
Note: duplicate definition of program class [com.sun.jna.InvocationMapper]
Note: duplicate definition of program class [com.sun.jna.JNIEnv]
Note: duplicate definition of program class [com.sun.jna.Klass]
Note: duplicate definition of program class [com.sun.jna.LastErrorException]
Note: duplicate definition of program class [com.sun.jna.Library$Handler$FunctionInfo]
Note: duplicate definition of program class [com.sun.jna.Library$Handler]
Note: duplicate definition of program class [com.sun.jna.Library]
Note: duplicate definition of program class [com.sun.jna.Memory$LinkedReference]
Note: duplicate definition of program class [com.sun.jna.Memory$SharedMemory]
Note: duplicate definition of program class [com.sun.jna.Memory]
Note: duplicate definition of program class [com.sun.jna.MethodParameterContext]
Note: duplicate definition of program class [com.sun.jna.MethodResultContext]
Note: duplicate definition of program class [com.sun.jna.Native$1]
Note: duplicate definition of program class [com.sun.jna.Native$2]
Note: duplicate definition of program class [com.sun.jna.Native$3]
Note: duplicate definition of program class [com.sun.jna.Native$4]
Note: duplicate definition of program class [com.sun.jna.Native$5]
Note: duplicate definition of program class [com.sun.jna.Native$6]
Note: duplicate definition of program class [com.sun.jna.Native$7]
Note: duplicate definition of program class [com.sun.jna.Native$AWT]
Note: duplicate definition of program class [com.sun.jna.Native$Buffers]
Note: duplicate definition of program class [com.sun.jna.Native$ffi_callback]
Note: duplicate definition of program class [com.sun.jna.Native]
Note: duplicate definition of program class [com.sun.jna.NativeLibrary$1]
Note: duplicate definition of program class [com.sun.jna.NativeLibrary$2]
Note: duplicate definition of program class [com.sun.jna.NativeLibrary]
Note: duplicate definition of program class [com.sun.jna.NativeLong]
Note: duplicate definition of program class [com.sun.jna.NativeMapped]
Note: duplicate definition of program class [com.sun.jna.NativeMappedConverter]
Note: duplicate definition of program class [com.sun.jna.NativeString$StringMemory]
Note: duplicate definition of program class [com.sun.jna.NativeString]
Note: duplicate definition of program class [com.sun.jna.Platform]
Note: duplicate definition of program class [com.sun.jna.Pointer$1]
Note: duplicate definition of program class [com.sun.jna.Pointer$Opaque]
Note: duplicate definition of program class [com.sun.jna.Pointer]
Note: duplicate definition of program class [com.sun.jna.PointerType]
Note: duplicate definition of program class [com.sun.jna.StringArray]
Note: duplicate definition of program class [com.sun.jna.Structure$1]
Note: duplicate definition of program class [com.sun.jna.Structure$2]
Note: duplicate definition of program class [com.sun.jna.Structure$3]
Note: duplicate definition of program class [com.sun.jna.Structure$AutoAllocated]
Note: duplicate definition of program class [com.sun.jna.Structure$ByReference]
Note: duplicate definition of program class [com.sun.jna.Structure$ByValue]
Note: duplicate definition of program class [com.sun.jna.Structure$FFIType$FFITypes]
Note: duplicate definition of program class [com.sun.jna.Structure$FFIType$size_t]
Note: duplicate definition of program class [com.sun.jna.Structure$FFIType]
Note: duplicate definition of program class [com.sun.jna.Structure$FieldOrder]
Note: duplicate definition of program class [com.sun.jna.Structure$LayoutInfo]
Note: duplicate definition of program class [com.sun.jna.Structure$NativeStringTracking]
Note: duplicate definition of program class [com.sun.jna.Structure$StructField]
Note: duplicate definition of program class [com.sun.jna.Structure$StructureSet]
Note: duplicate definition of program class [com.sun.jna.Structure]
Note: duplicate definition of program class [com.sun.jna.StructureReadContext]
Note: duplicate definition of program class [com.sun.jna.StructureWriteContext]
Note: duplicate definition of program class [com.sun.jna.ToNativeContext]
Note: duplicate definition of program class [com.sun.jna.ToNativeConverter]
Note: duplicate definition of program class [com.sun.jna.TypeConverter]
Note: duplicate definition of program class [com.sun.jna.TypeMapper]
Note: duplicate definition of program class [com.sun.jna.Union]
Note: duplicate definition of program class [com.sun.jna.VarArgsChecker$1]
Note: duplicate definition of program class [com.sun.jna.VarArgsChecker$NoVarArgsChecker]
Note: duplicate definition of program class [com.sun.jna.VarArgsChecker$RealVarArgsChecker]
Note: duplicate definition of program class [com.sun.jna.VarArgsChecker]
Note: duplicate definition of program class [com.sun.jna.Version]
Note: duplicate definition of program class [com.sun.jna.WString]
Note: duplicate definition of program class [com.sun.jna.WeakMemoryHolder]
Note: duplicate definition of resource file [com/sun/jna/aix-ppc/libjnidispatch.a]
Note: duplicate definition of resource file [com/sun/jna/aix-ppc64/libjnidispatch.a]
Note: duplicate definition of resource file [com/sun/jna/darwin-aarch64/libjnidispatch.jnilib]
Note: duplicate definition of resource file [com/sun/jna/darwin-x86-64/libjnidispatch.jnilib]
Note: duplicate definition of resource file [com/sun/jna/freebsd-x86-64/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/freebsd-x86/libjnidispatch.so]
Note: duplicate definition of program class [com.sun.jna.internal.ReflectionUtils]
Note: duplicate definition of resource file [com/sun/jna/linux-aarch64/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/linux-arm/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/linux-armel/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/linux-mips64el/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/linux-ppc/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/linux-ppc64le/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/linux-riscv64/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/linux-s390x/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/linux-x86-64/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/linux-x86/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/openbsd-x86-64/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/openbsd-x86/libjnidispatch.so]
Note: duplicate definition of program class [com.sun.jna.ptr.ByReference]
Note: duplicate definition of program class [com.sun.jna.ptr.ByteByReference]
Note: duplicate definition of program class [com.sun.jna.ptr.DoubleByReference]
Note: duplicate definition of program class [com.sun.jna.ptr.FloatByReference]
Note: duplicate definition of program class [com.sun.jna.ptr.IntByReference]
Note: duplicate definition of program class [com.sun.jna.ptr.LongByReference]
Note: duplicate definition of program class [com.sun.jna.ptr.NativeLongByReference]
Note: duplicate definition of program class [com.sun.jna.ptr.PointerByReference]
Note: duplicate definition of program class [com.sun.jna.ptr.ShortByReference]
Note: duplicate definition of resource file [com/sun/jna/sunos-sparc/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/sunos-sparcv9/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/sunos-x86-64/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/sunos-x86/libjnidispatch.so]
Note: duplicate definition of resource file [com/sun/jna/win32-aarch64/jnidispatch.dll]
Note: duplicate definition of resource file [com/sun/jna/win32-x86-64/jnidispatch.dll]
Note: duplicate definition of resource file [com/sun/jna/win32-x86/jnidispatch.dll]
Note: duplicate definition of program class [com.sun.jna.win32.DLLCallback]
Note: duplicate definition of program class [com.sun.jna.win32.StdCall]
Note: duplicate definition of program class [com.sun.jna.win32.StdCallFunctionMapper]
Note: duplicate definition of program class [com.sun.jna.win32.StdCallLibrary$StdCallCallback]
Note: duplicate definition of program class [com.sun.jna.win32.StdCallLibrary]
Note: duplicate definition of program class [com.sun.jna.win32.W32APIFunctionMapper]
Note: duplicate definition of program class [com.sun.jna.win32.W32APIOptions$1]
Note: duplicate definition of program class [com.sun.jna.win32.W32APIOptions$2]
Note: duplicate definition of program class [com.sun.jna.win32.W32APIOptions]
Note: duplicate definition of program class [com.sun.jna.win32.W32APITypeMapper$1]
Note: duplicate definition of program class [com.sun.jna.win32.W32APITypeMapper$2]
Note: duplicate definition of program class [com.sun.jna.win32.W32APITypeMapper]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/LICENSE]
Note: duplicate definition of resource file [META-INF/NOTICE]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [license/LICENSE]
Note: duplicate definition of resource file [license/LICENSE.dom-documentation.txt]
Note: duplicate definition of resource file [license/LICENSE.dom-software.txt]
Note: duplicate definition of resource file [license/NOTICE]
Note: duplicate definition of resource file [license/README.dom.txt]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/MANIFEST.MF]
Note: duplicate definition of resource file [META-INF/LICENSE.txt]
Note: duplicate definition of resource file [META-INF/NOTICE.txt]
Unexpected error
java.io.IOException: Can't read [/usr/lib/jvm/java-20-amazon-corretto/jmods/jdk.zipfs.jmod(;;;;;;;!**.jar;!module-info.class)] (Can't process class [jdk/nio/zipfs/ByteArrayChannel.class] (Unsupported version number [64.0] (maximum 62.65535, Java 18)))
	at proguard.InputReader.readInput(InputReader.java:269) ~[proguard-base-7.2.2.jar:7.2.2]
	at proguard.InputReader.readInput(InputReader.java:233) ~[proguard-base-7.2.2.jar:7.2.2]
	at proguard.InputReader.readInput(InputReader.java:210) ~[proguard-base-7.2.2.jar:7.2.2]
	at proguard.InputReader.execute(InputReader.java:162) ~[proguard-base-7.2.2.jar:7.2.2]
	at proguard.pass.PassRunner.run(PassRunner.java:24) ~[proguard-base-7.2.2.jar:7.2.2]
	at proguard.ProGuard.readInput(ProGuard.java:309) ~[proguard-base-7.2.2.jar:7.2.2]
	at proguard.ProGuard.execute(ProGuard.java:111) ~[proguard-base-7.2.2.jar:7.2.2]
	at proguard.ProGuard.main(ProGuard.java:623) [proguard-base-7.2.2.jar:7.2.2]
Caused by: java.io.IOException: Can't process class [jdk/nio/zipfs/ByteArrayChannel.class] (Unsupported version number [64.0] (maximum 62.65535, Java 18))
	at proguard.io.ClassReader.read(ClassReader.java:118) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.RenamedDataEntryReader.read(RenamedDataEntryReader.java:97) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.PrefixStrippingDataEntryReader.read(PrefixStrippingDataEntryReader.java:61) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.PrefixStrippingDataEntryReader.read(PrefixStrippingDataEntryReader.java:61) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.JarReader.read(JarReader.java:84) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.DirectorySource.readFiles(DirectorySource.java:68) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.DirectorySource.pumpDataEntries(DirectorySource.java:54) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.InputReader.readInput(InputReader.java:265) ~[proguard-base-7.2.2.jar:7.2.2]
	... 7 more
Caused by: java.lang.UnsupportedOperationException: Unsupported version number [64.0] (maximum 62.65535, Java 18)
	at proguard.classfile.util.ClassUtil.checkVersionNumbers(ClassUtil.java:167) ~[proguard-core-9.0.1.jar:?]
	at proguard.classfile.io.LibraryClassReader.visitLibraryClass(LibraryClassReader.java:86) ~[proguard-core-9.0.1.jar:?]
	at proguard.classfile.LibraryClass.accept(LibraryClass.java:408) ~[proguard-core-9.0.1.jar:?]
	at proguard.io.ClassReader.read(ClassReader.java:90) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.RenamedDataEntryReader.read(RenamedDataEntryReader.java:97) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.PrefixStrippingDataEntryReader.read(PrefixStrippingDataEntryReader.java:61) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.PrefixStrippingDataEntryReader.read(PrefixStrippingDataEntryReader.java:61) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.JarReader.read(JarReader.java:84) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.DirectorySource.readFiles(DirectorySource.java:68) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.io.DirectorySource.pumpDataEntries(DirectorySource.java:54) ~[proguard-core-9.0.1.jar:7.2.2]
	at proguard.InputReader.readInput(InputReader.java:265) ~[proguard-base-7.2.2.jar:7.2.2]
	... 7 more
```
Any clue as to why the build could have failed?

**Comment by Koitharu** [comment]
Try jdk 11..18, looks like newer versions are not supported

**Comment by tabledrop** [comment]
Build succeeded with `java-17-openjdk`. Thank you for the suggestion!
